# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Cosmos"
license = "MIT"
licenselink = "https://github.com/SimpCosm/hugo-theme-cosmos/blob/master/LICENSE"
description = "A new life style Hugo theme in cosmos"
homepage = "https://houmin.cc/hugo-theme-cosmos"
min_version = "0.41.0"

tags = [
  "blog",
  "minimalist",
]

features = [
  "blog",
  "favicon",
  "scroll-to-top"
]

[author]
  name = "Houmin Wei"
  homepage = "https://github.com/SimpCosm"

# If porting an existing theme
[original]
  name = "PaperMod"
  homepage = "https://adityatelange.github.io/hugo-PaperMod"
  repo = "https://github.com/adityatelange/hugo-PaperMod"
